modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=" "
[[mods]]
    modId="sunblockcore"
    version="0.7.2-1.20.1"
    displayName="SunBlockCore"
    displayURL="https://sunblockone.milieux.ca"
    authors="Shahrom Ali, Ella Noyes, Stuart Thiel"
    description='''The core mod for SunBlock - the solar-powered minecraft server.'''

[[dependencies.sunblockcore]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sunblockcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
