modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"
issueTrackerURL=" "
[[mods]]
    modId="sunblockcore"
    version="${mod_version}"
    displayName="SunBlockCore"
    displayURL="https://sunblock.milieux.ca"
    authors="Shahrom Ali, Andrew, Ella Noyes, and Stuart Thiel"
    description='''The core mod for SunBlock - the solar-powered minecraft server.'''

[[dependencies.sunblockcore]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.sunblockcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"
